language: c
before_install:
   - sudo apt-get update -qq
   - sudo apt-get install -qq texinfo
   - sudo apt-get install libgmp3-dev libmpfr4 libmpfr-dev
script:
  - ./configure && make && make check

