language: c
before_install:
   - sudo apt-get update -qq
   - sudo apt-get install -qq texinfo
   - sudo apt-get install libgmp3-dev libmpfr4 libmpfr-dev
script:
  - ./.build_dependencies && ./configure --with-mpir=mpir-2.7.0 --with-mpfr=mpfr-3.1.3 && make && make check

