language: c
sudo: false
addons:
  apt:
    packages:
      - texinfo

os:
  - osx
  - linux

compiler:
  - gcc
  - clang

cache:
  directories:
  - $HOME/deps

script:
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]] && [[ "${CC}" == "gcc" ]]; then
        export CC=gcc-4.8;
        export CXX=g++-4.8;
    fi
  - echo "int flint_test_multiplier(){return 1;}" > test_helpers.c
  - if [ ! -d "$HOME/deps" ]; then 
        ./.build_dependencies;
    fi
  - ./configure --with-mpir=$HOME/deps --with-mpfr=$HOME/deps && make -j4 && make -j4 check

